// src/components/about.tsx
import { component$ } from '@builder.io/qwik';

export default component$(() => {
	return (
		<div id='about-me' class='bg-white dark:bg-gray-800 md:p-20'>
			<div class='grid grid-cols-1 md:rounded-md md:border-solid md:border-2 md:border-gray-500 dark:border-gray-300'>
				<img
					class='pt-10 mx-auto'
					src='./profile_300x300.webp'
					alt='Giorgio Boa profile picture'
          width='300'
          height='300'
				/>
				<div>
					<div class='text-2xl md:text-4xl font-bold py-[30px] text-center text-gray-700 dark:text-gray-400'>
						About Me
					</div>
					<div class='px-20 text-xl text-gray-700 dark:text-gray-400'>
						I'm a full stack developer and the front-end ecosystem is my
						passion. I started to develop application in 2006 and in 2012 I fall
						in love with JavaScript
						<br />
						<br />
						I'm active in open source ecosystem, I love learn and study new
						things
						<br />
						I also really enjoy public speaking and sharing my experiences
						<br />
						I'm very ambitious and I try to improve myself every day 🚀
						<br />
						<br />
						👇 I'm giving FREE mentoring
						<br />
						In all these years I learned a lot from communities and open source
						❤️
						<br />
						Now I want to give something back in my spare time 💪
						<br />
						<br />
						<a href='https://mentorcruise.com/mentor/giorgioboa/'>
							<img
								src='https://cdn.mentorcruise.com/img/banner/sky-sm.svg'
								width='240'
								height='240'
								alt='MentorCruise'
							/>
						</a>
						<br />
					</div>
				</div>
			</div>
		</div>
	);
});

// src/lib/About.svelte
<div id="about-me" class="bg-white dark:bg-gray-800 md:p-20">
	<div
		class="grid grid-cols-1 lg:grid-cols-2 rounded-md border-solid border-2 border-gray-500 dark:border-gray-300"
	>
		<img
			class="w-1/2 pt-10 md:pt-0 md:w-full mx-auto"
			src="https://raw.githubusercontent.com/gioboa/gioboa/master/profile_960x960.png"
			alt="Profile pic"
		/>
		<div>
			<div
				class="text-2xl md:text-4xl font-bold py-[30px] text-center text-gray-700 dark:text-gray-400"
			>
				About Me
			</div>
			<div class="px-20 text-xl text-gray-700 dark:text-gray-400">
				I'm a full stack developer and the front-end ecosystem is my passion. I
				started to develop application in 2006 and in 2012 I fall in love with
				JavaScript<br /><br />
				I'm active in open source ecosystem, I love learn and study new things
				<br />
				I also really enjoy public speaking and sharing my experiences
				<br />
				I'm very ambitious and I try to improve myself every day 🚀
				<br /><br />
				👇 I'm giving FREE mentoring<br />
				In all these years I learned a lot from communities and open source ❤️
				<br />
				Now I want to give something back in my spare time 💪
				<br /><br />
				<a href="https://mentorcruise.com/mentor/giorgioboa/">
					<img
						src="https://cdn.mentorcruise.com/img/banner/sky-sm.svg"
						width="240"
						alt="MentorCruise"
					/>
				</a><br />
			</div>
		</div>
	</div>
</div>
